sudo: false

language: ruby
rvm:
- 2.1

env:
  global:
    # speeds up installation of html-proofer
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - npm install
  - npm install -g gulp
  - gem install jekyll jekyll-paginate html-proofer

script:
  - gulp build
  - ls
  - ls ./_site
  - rm -R ./_site/node_modules
  - htmlproofer ./_site --disable-external
