baseURL = "http://lifelongstudent.io/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Stories of a Lifelong Student"
theme = "LoveIt"
enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

copyright = "The Docsy Authors"
privacy_policy = "https://policies.google.com/privacy"

[params]
  # LoveIt theme version
  version = "0.1.X"
  # site description
  description = "Stories of a Lifelong Student Description"
  # site keywords
  keywords = ["computer science", "data structures", "algorithms", "computer networks", "operating system", "machine learning", "open source", "linux", "arduino", "programming", "security", "pen testing", "hacking", "android", "reverse engineering"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/nirgn975/stories-of-a-lifelong-student"
  # LoveIt   v0.1.1
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # Header info
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
  # Footer Copyright Info
  [params.footer]
    # Site creation time
    since = 2012
    # ICP info only in China (HTML format is allowed)
    icp = ""
    # license info (HTML format is allowed)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # Home Page Info
  [params.home]
    # Home Page Profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/logo.png"
      # subtitle shown in home page
      subtitle = "Welcome to Stories of a Lifelong Student, a blog for geeks (:"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
    # Home Page Posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false
  # Social Info in home page
  [params.social]
    GitHub = "nirgn975"
    Linkedin = "nirgn"
    Twitter = "nirgn975"
    Email = "nir@galon.io"
    Medium = "@nirgn"
    Keybase = "nirgn975"
    Reddit = "nirgn975"
    Stackoverflow = "2040160/nirgn"
  # Page config
  [params.page]
    # whether to use lightgallery in the page
    lightgallery = true
    # whether to show link to Raw Markdown content of the post
    linkToMarkdown = true
  # mathematical formulas (KaTeX https://katex.org/)
  [params.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # Social Share Links in post page
  [params.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = true
    Whatsapp = true
    Reddit = true
  # Comment Config
  [params.comment]
    enable = true

  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    baidu = ""
  # Publisher Info just for SEO
  [params.publisher]
    name = "Nir Galon"
    [params.publisher.logo]
      url = "/images/publisher/nir-galon.jpg"
      width = 127
      height = 40
  # Website Log Info just for SEO
  [params.logo]
    url = "/images/logo.png"
    width = 127
    height = 40
  # Website Image Info just for SEO
  [params.image]
    url = "/images/logo.png"
    width = 800
    height = 600
  # CSS and JS Files CDN
  [params.cdn]
    # fontawesome-free@5.12.1 https://fontawesome.com/
    fontawesomeFreeCSS = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'
    # animate.css@3.7.2 https://github.com/daneden/animate.css
    animateCSS = 'https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css'
    # smooth-scroll@16.1.2 https://github.com/cferdinandi/smooth-scroll
    smoothScrollJS = 'https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll@16.1.2/dist/smooth-scroll.min.js'
    # sharer@0.4.0 https://github.com/ellisonleao/sharer.js
    sharerJS = 'https://cdnjs.cloudflare.com/ajax/libs/sharer.js/0.4.0/sharer.min.js'
    # lazysizes@5.2.0 https://github.com/aFarkas/lazysizes
    lazysizesJS = 'https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.2.0/lazysizes.min.js'
    # lightgallery@1.1.3 lg-thumbnail@1.1.0 lg-zoom@1.1.0 https://github.com/sachinchoolur/lightgallery.js
    lightgalleryCSS = 'https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.1.3/css/lightGallery.css'
    lightgalleryJS = 'https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.1.3/js/lightGallery.min.js'
    lightgalleryThumbnailJS = 'https://cdnjs.cloudflare.com/ajax/libs/lg-thumbnail/1.1.0/lg-thumbnail.min.js'
    lightgalleryZoomJS = 'https://cdnjs.cloudflare.com/ajax/libs/lg-zoom/1.1.0/lg-zoom.min.js'
    # typeit@6.5.1 https://github.com/alexmacarthur/typeit
    typeitJS = 'https://cdnjs.cloudflare.com/ajax/libs/typeit/6.5.1/typeit.min.js'
    # katex@0.11.1 https://github.com/KaTeX/KaTeX
    katexCSS = 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.css'
    katexJS = 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.js'
    katexAutoRenderJS = 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/contrib/auto-render.min.js'
    katexCopyTexCSS = 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/contrib/copy-tex.min.css'
    katexCopyTexJS = 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/contrib/copy-tex.min.js'
    katexMhchemJS = 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/contrib/mhchem.min.js'
    # mermaid@8.4.8 https://github.com/knsv/mermaid
    mermaidJS = 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.8/mermaid.js'
    # aplayer@1.10.1 https://github.com/MoePlayer/APlayer
    aplayerCSS = 'https://cdnjs.cloudflare.com/ajax/libs/aplayer/1.10.1/APlayer.min.css'
    aplayerJS = 'https://cdnjs.cloudflare.com/ajax/libs/aplayer/1.10.1/APlayer.min.js'
    # meting@2.0.1 https://github.com/metowolf/MetingJS
    metingJS = 'https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js'
    # echarts@4.6.0 https://echarts.apache.org/
    echartsJS = 'https://cdnjs.cloudflare.com/ajax/libs/echarts/4.6.0/echarts.min.js'
    echartsMacaronsJS = ''
    # gitalk@1.6.2 https://github.com/gitalk/gitalk
    gitalkCSS = 'https://cdnjs.cloudflare.com/ajax/libs/gitalk/1.6.2/gitalk.min.css'
    gitalkJS = 'https://cdnjs.cloudflare.com/ajax/libs/gitalk/1.6.2/gitalk.min.js'

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
[author]
  name = "Nir Galon"
  link = "https://nir.galon.io/"

# Sitemap Info
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = ":year/:month/:filename"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is allowed), such as icons
    pre = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    name = "About"
    url = "/about"
    title = "About"
    weight = 4
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    name = ""
    url = "https://github.com/nirgn975"
    title = "GitHub"
    weight = 5
